# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: pythonVersion
    value: '3.8'
  - group: devops-ai-agent-group

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "API Key passed"
  env:
    OPENAI_API_KEY: $(OPENAI_API_KEY)

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '.'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(Pipeline.Workspace)'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'my-app-ado-con'
    appName: 'hello-ai-flask'
    package: '$(Pipeline.Workspace)/drop/app.zip'
